name: run tests

on:
  pull_request:
  push:
    branches:
      - 'master'

jobs:
  test:

    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        node-version:
          - 16.16.x
        platform:
          - ubuntu-latest

    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017

      redis:
        image: redis:latest
        ports:
          - 6379:6379

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: setup node env
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: npm install
        run: npm install

      - name: Setup .env for test
        run: |
          cp .env.sample .env.test
          echo $'\nTEST=true' >> .env.test

      - name: run tests
        run: npm test
